#!/bin/sh
# Gradle wrapper script — auto-downloads gradle if not present
# In a real project, this is generated by `gradle wrapper`

APP_NAME="Gradle"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
GRADLE_VERSION="8.9"
DIST_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"

warn () { echo "$*"; }
die () { echo; echo "  $*"; echo; exit 1; }

# Determine the project base directory
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

# Use the Gradle wrapper jar if available
if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    exec java $JAVA_OPTS \
        -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain "$@"
else
    echo "Gradle wrapper jar not found."
    echo "Run 'gradle wrapper' in the project root to generate it,"
    echo "or open this project in Android Studio which handles it automatically."
    exit 1
fi
